runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static
<<<<<<< HEAD
=======

  
>>>>>>> 071a560366e4ae3a5d1431d1e17da202a9df0b5a
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest


  